# Generated by Django 4.2.9 on 2024-08-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('product', '0007_product_delivery_charges_product_related_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropoffpoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_points', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
